// <auto-generated />
namespace LearnAspNetMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateItemsTablesLinkingToApplicationDbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateItemsTablesLinkingToApplicationDbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061534549_UpdateItemsTablesLinkingToApplicationDbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
